title: The green place
email: 

baseurl: https://teodora-petkova.github.io/Jekyll-Portfolio-Theme/
url: / #Leave this, change the baseurl.

destination: _site

collections:
  My_first_comics:
    output: true
  Coincidence:
    output: true
  Sketches:
    output: true
collections_dir: collections
